const fs = require('fs');

const writeStream = fs.createWriteStream('./dist/_headers');

const headers = `# These are headers generated by headers.js
/luna.6cb71025.jpg
    Cache-Control: public, max-age=31536000\n
`;

console.log('writing these headers:\n ', headers);
writeStream.write(headers);
writeStream.end();
