const fs = require('fs');

if (process.env.CONTEXT === 'branch-deploy') {
  const writeStream = fs.createWriteStream('./dist/_headers');

  const headers = `# These are headers generated by headers.js
/*
  Basic-Auth: test:password
`;

  console.log('writing headers for password protection\n ', headers);
  writeStream.write(headers);
  writeStream.end();
}
